# Generated by Django 4.2.1 on 2023-07-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hms_user',
            name='id',
        ),
        migrations.AddField(
            model_name='hms_user',
            name='userId',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
